### ISSUE TITLE
Mario Koopa Blast 1-2 pipe issue

### ISSUE THREAD

**Issue by GlaberTwin** [GlaberTwin/SRB2ThePast#53]
![image](https://github.com/GlaberTwin/SRB2ThePast/assets/154749270/0547d5aa-e061-4716-82a3-fd256f948897)

apparently if you hit the pipe just right, you can get mis-aligned and be unable to use the pipe.

**Comment by BarrelsOFun** [comment]
Tested with the character in question and it is in fact Neo Sonic's homing attack causing the issues.
![srb20811](https://github.com/GlaberTwin/SRB2ThePast/assets/161785144/ad05b61f-e5f1-486d-96ab-7549f9e26ae1)
Here's first person footage and notice how he wiggles when homing.

**Comment by BarrelsOFun** [comment]
![srb20823](https://github.com/GlaberTwin/SRB2ThePast/assets/161785144/136b75d9-a67e-474d-bc83-1ad40a64c125)
Goombas at the end specifically (watch Y coordinate)

**Comment by BarrelsOFun** [comment]
It is in fact, just a homing character thing.

https://github.com/GlaberTwin/SRB2ThePast/assets/161785144/265b8054-4479-45b2-a261-b2576539e2e5

Here's 2.0 footage of going way off the map with homing as the Charability.

**Comment by GlaberTwin** [comment]
so even it it was addressed with invisible walls along the pipe it would still result in the character breaking off the axis. Meaning this issue is effectively invalid.
